### ISSUE TITLE
question about pining the CPU and VM setup for qemu VMs

### ISSUE THREAD

**Issue by photoszzt** [vtess/Pond#2]
In the VM definition, each VM has 8 vcpus. Which version of QEMU does this experiment runs on? According to https://www.qemu.org/docs/master/system/qemu-manpage.html, there's different interpretation of what -smp 8 means for qemu to create the CPU topology. "For example, the following option(-smp 2) defines a machine board with 2 sockets of 1 core before 6.2 and 1 socket of 2 cores after 6.2" It would be great to specify the exact CPU topology on the argument. 

https://github.com/vtess/Pond/blob/e9ae753669f98497f36c9ba52525e062515c5bf1/bigdata/vm/pin.sh#L9-L14
On line 10, it pins the vcpu thread to core 0 to 9 while we only have 8 vcpus. 

On line 12, it said it pins the vcpu to the rest of the pCPUs but on line 14, it pins the qemu process to core 1 to 9 which overlaps the above range. Should it be on a different range or exactly the same range? Why 1-9 not 0-9?

**Comment by huaicheng** [comment]
This is an old script that needs to be updated. Please customize it for your physical machine layout. The rule of thumb, you want to match the VM vCPU topologies to pCPUs.
